package com.andi.model;
// Generated 7/05/2016 07:34:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AsuntoRelevante generated by hbm2java
 */
public class AsuntoRelevante  implements java.io.Serializable {


     private long asuntoId;
     private String asuntoNombre;
     private String asuntoTipo;
     private Set subsectorAsuntos = new HashSet(0);

    public AsuntoRelevante() {
    }

	
    public AsuntoRelevante(long asuntoId) {
        this.asuntoId = asuntoId;
    }
    public AsuntoRelevante(long asuntoId, String asuntoNombre, String asuntoTipo, Set subsectorAsuntos) {
       this.asuntoId = asuntoId;
       this.asuntoNombre = asuntoNombre;
       this.asuntoTipo = asuntoTipo;
       this.subsectorAsuntos = subsectorAsuntos;
    }
   
    public long getAsuntoId() {
        return this.asuntoId;
    }
    
    public void setAsuntoId(long asuntoId) {
        this.asuntoId = asuntoId;
    }
    public String getAsuntoNombre() {
        return this.asuntoNombre;
    }
    
    public void setAsuntoNombre(String asuntoNombre) {
        this.asuntoNombre = asuntoNombre;
    }
    public String getAsuntoTipo() {
        return this.asuntoTipo;
    }
    
    public void setAsuntoTipo(String asuntoTipo) {
        this.asuntoTipo = asuntoTipo;
    }
    public Set getSubsectorAsuntos() {
        return this.subsectorAsuntos;
    }
    
    public void setSubsectorAsuntos(Set subsectorAsuntos) {
        this.subsectorAsuntos = subsectorAsuntos;
    }




}


