package com.andi.model;
// Generated 7/05/2016 07:34:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dimension generated by hbm2java
 */
public class Dimension  implements java.io.Serializable {


     private long dimensionId;
     private String dimensionDescripcion;
     private Set recomendacions = new HashSet(0);

    public Dimension() {
    }

	
    public Dimension(long dimensionId) {
        this.dimensionId = dimensionId;
    }
    public Dimension(long dimensionId, String dimensionDescripcion, Set recomendacions) {
       this.dimensionId = dimensionId;
       this.dimensionDescripcion = dimensionDescripcion;
       this.recomendacions = recomendacions;
    }
   
    public long getDimensionId() {
        return this.dimensionId;
    }
    
    public void setDimensionId(long dimensionId) {
        this.dimensionId = dimensionId;
    }
    public String getDimensionDescripcion() {
        return this.dimensionDescripcion;
    }
    
    public void setDimensionDescripcion(String dimensionDescripcion) {
        this.dimensionDescripcion = dimensionDescripcion;
    }
    public Set getRecomendacions() {
        return this.recomendacions;
    }
    
    public void setRecomendacions(Set recomendacions) {
        this.recomendacions = recomendacions;
    }




}


