package com.andi.model;
// Generated 7/05/2016 07:34:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Oportunidad generated by hbm2java
 */
public class Oportunidad  implements java.io.Serializable {


     private long oportunidadId;
     private String oportunidadDescripcion;
     private String oportunidadTipo;
     private Set subsectorOportunidads = new HashSet(0);

    public Oportunidad() {
    }

	
    public Oportunidad(long oportunidadId) {
        this.oportunidadId = oportunidadId;
    }
    public Oportunidad(long oportunidadId, String oportunidadDescripcion, String oportunidadTipo, Set subsectorOportunidads) {
       this.oportunidadId = oportunidadId;
       this.oportunidadDescripcion = oportunidadDescripcion;
       this.oportunidadTipo = oportunidadTipo;
       this.subsectorOportunidads = subsectorOportunidads;
    }
   
    public long getOportunidadId() {
        return this.oportunidadId;
    }
    
    public void setOportunidadId(long oportunidadId) {
        this.oportunidadId = oportunidadId;
    }
    public String getOportunidadDescripcion() {
        return this.oportunidadDescripcion;
    }
    
    public void setOportunidadDescripcion(String oportunidadDescripcion) {
        this.oportunidadDescripcion = oportunidadDescripcion;
    }
    public String getOportunidadTipo() {
        return this.oportunidadTipo;
    }
    
    public void setOportunidadTipo(String oportunidadTipo) {
        this.oportunidadTipo = oportunidadTipo;
    }
    public Set getSubsectorOportunidads() {
        return this.subsectorOportunidads;
    }
    
    public void setSubsectorOportunidads(Set subsectorOportunidads) {
        this.subsectorOportunidads = subsectorOportunidads;
    }




}


