package com.andi.model;
// Generated 7/05/2016 07:34:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private long preguntaId;
     private String preguntaDescripcion;
     private Long preguntaPredecesora;
     private Long preguntaPadre;
     private Long preguntaCuestionario;
     private Set respuestaPreguntas = new HashSet(0);
     private String respuesta;
     private String clase;

    public Pregunta() {
        clase = "display:none !important;";
    }

	
    public Pregunta(long preguntaId) {
        this.preguntaId = preguntaId;
    }
    public Pregunta(long preguntaId, String preguntaDescripcion, Long preguntaPredecesora, Long preguntaPadre, Long preguntaCuestionario, Set respuestaPreguntas) {
       this.preguntaId = preguntaId;
       this.preguntaDescripcion = preguntaDescripcion;
       this.preguntaPredecesora = preguntaPredecesora;
       this.preguntaPadre = preguntaPadre;
       this.preguntaCuestionario = preguntaCuestionario;
       this.respuestaPreguntas = respuestaPreguntas;
    }
   
    public long getPreguntaId() {
        return this.preguntaId;
    }
    
    public void setPreguntaId(long preguntaId) {
        this.preguntaId = preguntaId;
    }
    public String getPreguntaDescripcion() {
        return this.preguntaDescripcion;
    }
    
    public void setPreguntaDescripcion(String preguntaDescripcion) {
        this.preguntaDescripcion = preguntaDescripcion;
    }
    public Long getPreguntaPredecesora() {
        return this.preguntaPredecesora;
    }
    
    public void setPreguntaPredecesora(Long preguntaPredecesora) {
        this.preguntaPredecesora = preguntaPredecesora;
    }
    public Long getPreguntaPadre() {
        return this.preguntaPadre;
    }
    
    public void setPreguntaPadre(Long preguntaPadre) {
        this.preguntaPadre = preguntaPadre;
    }
    public Long getPreguntaCuestionario() {
        return this.preguntaCuestionario;
    }
    
    public void setPreguntaCuestionario(Long preguntaCuestionario) {
        this.preguntaCuestionario = preguntaCuestionario;
    }
    public Set getRespuestaPreguntas() {
        return this.respuestaPreguntas;
    }
    
    public void setRespuestaPreguntas(Set respuestaPreguntas) {
        this.respuestaPreguntas = respuestaPreguntas;
    }

    /**
     * @return the respuesta
     */
    public String getRespuesta() {
        return respuesta;
    }

    /**
     * @param respuesta the respuesta to set
     */
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }

    /**
     * @return the clase
     */
    public String getClase() {
        return clase;
    }

    /**
     * @param clase the clase to set
     */
    public void setClase(String clase) {
        this.clase = clase;
    }




}


