package com.andi.model;
// Generated 7/05/2016 07:34:50 PM by Hibernate Tools 4.3.1



/**
 * RespuestaPregunta generated by hbm2java
 */
public class RespuestaPregunta  implements java.io.Serializable {


     private long respuestaId;
     private Pregunta pregunta;
     private String respuestaDescripcion;

    public RespuestaPregunta() {
    }

	
    public RespuestaPregunta(long respuestaId) {
        this.respuestaId = respuestaId;
    }
    public RespuestaPregunta(long respuestaId, Pregunta pregunta, String respuestaDescripcion) {
       this.respuestaId = respuestaId;
       this.pregunta = pregunta;
       this.respuestaDescripcion = respuestaDescripcion;
    }
   
    public long getRespuestaId() {
        return this.respuestaId;
    }
    
    public void setRespuestaId(long respuestaId) {
        this.respuestaId = respuestaId;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public String getRespuestaDescripcion() {
        return this.respuestaDescripcion;
    }
    
    public void setRespuestaDescripcion(String respuestaDescripcion) {
        this.respuestaDescripcion = respuestaDescripcion;
    }




}


