package com.andi.model;
// Generated 7/05/2016 07:34:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sector generated by hbm2java
 */
public class Sector  implements java.io.Serializable {


     private String sectorNombre;
     private Set subsectors = new HashSet(0);

    public Sector() {
    }

	
    public Sector(String sectorNombre) {
        this.sectorNombre = sectorNombre;
    }
    public Sector(String sectorNombre, Set subsectors) {
       this.sectorNombre = sectorNombre;
       this.subsectors = subsectors;
    }
   
    public String getSectorNombre() {
        return this.sectorNombre;
    }
    
    public void setSectorNombre(String sectorNombre) {
        this.sectorNombre = sectorNombre;
    }
    public Set getSubsectors() {
        return this.subsectors;
    }
    
    public void setSubsectors(Set subsectors) {
        this.subsectors = subsectors;
    }




}


