package com.andi.model;
// Generated 7/05/2016 07:34:50 PM by Hibernate Tools 4.3.1



/**
 * SubsectorAsunto generated by hbm2java
 */
public class SubsectorAsunto  implements java.io.Serializable {


     private long subsectorAsuntoId;
     private AsuntoRelevante asuntoRelevante;
     private Subsector subsector;

    public SubsectorAsunto() {
    }

	
    public SubsectorAsunto(long subsectorAsuntoId) {
        this.subsectorAsuntoId = subsectorAsuntoId;
    }
    public SubsectorAsunto(long subsectorAsuntoId, AsuntoRelevante asuntoRelevante, Subsector subsector) {
       this.subsectorAsuntoId = subsectorAsuntoId;
       this.asuntoRelevante = asuntoRelevante;
       this.subsector = subsector;
    }
   
    public long getSubsectorAsuntoId() {
        return this.subsectorAsuntoId;
    }
    
    public void setSubsectorAsuntoId(long subsectorAsuntoId) {
        this.subsectorAsuntoId = subsectorAsuntoId;
    }
    public AsuntoRelevante getAsuntoRelevante() {
        return this.asuntoRelevante;
    }
    
    public void setAsuntoRelevante(AsuntoRelevante asuntoRelevante) {
        this.asuntoRelevante = asuntoRelevante;
    }
    public Subsector getSubsector() {
        return this.subsector;
    }
    
    public void setSubsector(Subsector subsector) {
        this.subsector = subsector;
    }




}


