package com.andi.model;
// Generated 7/05/2016 07:34:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subsector generated by hbm2java
 */
public class Subsector  implements java.io.Serializable {


     private String subsectorNombre;
     private Sector sector;
     private Set subsectorAsuntos = new HashSet(0);
     private Set subsectorOportunidads = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set subsectorFocos = new HashSet(0);

    public Subsector() {
    }

	
    public Subsector(String subsectorNombre) {
        this.subsectorNombre = subsectorNombre;
    }
    public Subsector(String subsectorNombre, Sector sector, Set subsectorAsuntos, Set subsectorOportunidads, Set usuarios, Set subsectorFocos) {
       this.subsectorNombre = subsectorNombre;
       this.sector = sector;
       this.subsectorAsuntos = subsectorAsuntos;
       this.subsectorOportunidads = subsectorOportunidads;
       this.usuarios = usuarios;
       this.subsectorFocos = subsectorFocos;
    }
   
    public String getSubsectorNombre() {
        return this.subsectorNombre;
    }
    
    public void setSubsectorNombre(String subsectorNombre) {
        this.subsectorNombre = subsectorNombre;
    }
    public Sector getSector() {
        return this.sector;
    }
    
    public void setSector(Sector sector) {
        this.sector = sector;
    }
    public Set getSubsectorAsuntos() {
        return this.subsectorAsuntos;
    }
    
    public void setSubsectorAsuntos(Set subsectorAsuntos) {
        this.subsectorAsuntos = subsectorAsuntos;
    }
    public Set getSubsectorOportunidads() {
        return this.subsectorOportunidads;
    }
    
    public void setSubsectorOportunidads(Set subsectorOportunidads) {
        this.subsectorOportunidads = subsectorOportunidads;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getSubsectorFocos() {
        return this.subsectorFocos;
    }
    
    public void setSubsectorFocos(Set subsectorFocos) {
        this.subsectorFocos = subsectorFocos;
    }




}


